### ISSUE TITLE
The Peptide Masses at the Front End do contain white space which are annoying if someone wants to copy them

### ISSUE THREAD

**Issue by Luxxii** [mpc-bioinformatics/trypperdb-web#1]
E.G. Copying the weight `588.286739698` yields the following in the clip board: ` 588.286739698 `.

This should be easy to fix!

**Comment by di-hardt** [comment]
As you know this issue was fixed during the rebuild ;)
https://github.com/mpc-bioinformatics/macpepdb-web/commit/8b823168577bd1a91226a9135bba7ee4b804385b

Best,
Dirk
