### ISSUE TITLE
API working?

### ISSUE THREAD

**Issue by Frostman300** [mpc-bioinformatics/trypperdb-web#3]
Peptide query...

http://localhost/api/peptides/LAQDGAHVVVSSR

yields...

Not Found
The requested URL was not found on this server.
Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/8.1.10 Server at localhost Port 80

I'm new to using APIs so maybe I'm missing something...

Brian

**Comment by di-hardt** [comment]
Hey Brian,

do you have a local instance of MaCPepDB running? If not you need to adjust the address: `https://macpepdb.mpc.rub.de/api/peptides/LAQDGAHVVVSSR`

Best,
Dirk

**Comment by Frostman300** [comment]
That works.
Thanks!
